# -*- coding: utf-8 -*-
"""ML Capstone Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uFAIX9-bjt1tzswtdvG5hBWym_eVsi-b

**Problem Statement-**

**The organization is experiencing a noticeable increase in employee attrition, which is leading to:**

-Increased hiring and onboarding costs
-Loss of experienced workforce
-Reduced productivity and team stability
-Impact on overall business performance

**Build a machine learning solution to:**
-Predict whether an employee will leave (Attrition: Yes/No)
-Identify key factors driving attrition
-Provide actionable insights to HR
"""

# Import libraries which required for project

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split,cross_validate, StratifiedKFold, GridSearchCV
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix,precision_score,f1_score,recall_score

# Load data set
df=pd.read_csv('/content/HR-Employee-Attrition.csv')
df.head()

df.shape

df.info()

df.describe().T

# EDA steps - Check null values and duplciates records in data set.
df.isnull().sum()

df.duplicated().sum()

# Clean uninformative columns/feature (constant or unique IDs) -It does not add any values in our data science/model

drop_cols=['EmployeeCount','EmployeeNumber','Over18','StandardHours']
df.drop(drop_cols,axis=1,inplace=True)
df.head()

df.shape

# Split the dataset into categorical and numerical columns
cat=df.select_dtypes(include='object')
num=df.select_dtypes(exclude='object')

## Outlier detection

def cap_outlier(series):
  Q1 = series.quantile(0.25)
  Q3 = series.quantile(0.75)
  IQR = Q3 - Q1

  UB = Q3 + (1.5 * IQR)
  LB = Q1 - (1.5 * IQR)

  return series.clip(LB, UB)

for col in num:
  df[col] = cap_outlier(df[col])

print('Outliers capped')
df.describe().T

#Categorical to numerical conversion using Label encoder
le=LabelEncoder()
for col in cat:
  df[col]=le.fit_transform(df[col])
df.head()

## Univariate analysis
df.hist(figsize=(20,20))
plt.show()

## correlation matrix

# Correlation matrix
corr = df.corr(numeric_only=True)

plt.figure(figsize=(20, 18))  # Increase figure size

sns.heatmap(
    corr,
    annot=True,        # Show values in each cell
    fmt=".2f",         # Display 2 decimal places
    cmap="coolwarm",   # Color scheme
    linewidths=0.5,    # Add lines between cells
    square=True,       # Make cells square
    cbar=True          # Show color bar
)

plt.xticks(rotation=45, ha="right")
plt.yticks(rotation=0)
plt.title("Correlation Heatmap")
plt.tight_layout()
plt.show()

### Split the dataset into x,y
x=df.drop('Attrition',axis=1)
y=df['Attrition']

## train test split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

## standardize the dataset

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

x_train

## Multi model cross validation
models = {
    'Logistic Regression': LogisticRegression(),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Naive Bayes': GaussianNB(),
    'K-Nearest Neighbors': KNeighborsClassifier()
}

cv = StratifiedKFold(n_splits=5, shuffle=True)
score = ['accuracy', 'precision', 'recall', 'f1']

cv_results = []

print("Running 5 fold stratefied Cross validation")

for name, model in models.items():
  scores = cross_validate(model, x_train, y_train, cv=cv, scoring=score)

  cv_results.append({
      'model': name,
      'accuracy': scores['test_accuracy'].mean(),
      'precision': scores['test_precision'].mean(),
      'recall': scores['test_recall'].mean(),
      'f1': scores['test_f1'].mean()
  })

cv_results = pd.DataFrame(cv_results).sort_values(by='f1', ascending=False)
print("\nCross validation results sorted by F1 score:")
print(cv_results.to_string(index=False))

## Final model selection - select top performing model based on F1 score

best_model = cv_results.iloc[0]['model']
print(f"\nBest performing model: {best_model}")

"""Train Model"""

best_model=models['Naive Bayes']

best_model.fit(x_train,y_train)

#make prediction

y_pred = best_model.predict(x_test)

#evaluate model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

# new employee onboarded
new_employee = {
    'Age': 32,
    'BusinessTravel': 2,
    'DailyRate': 850,
    'Department': 2,
    'DistanceFromHome': 8,
    'Education': 3,
    'EducationField': 3,
    'EnvironmentSatisfaction': 4,
    'Gender': 1,
    'HourlyRate': 5,
    'JobInvolvement': 3,
    'JobLevel': 2,
    'JobRole': 2,
    'JobSatisfaction': 4,
    'MaritalStatus': 0,
    'MonthlyIncome': 200,
    'MonthlyRate': 14500,
    'NumCompaniesWorked': 2,
    'OverTime': 100,
    'PercentSalaryHike': 14,
    'PerformanceRating': 3,
    'RelationshipSatisfaction': 3,
    'StockOptionLevel': 1,
    'TotalWorkingYears': 1,
    'TrainingTimesLastYear': 3,
    'WorkLifeBalance': 31,
    'YearsAtCompany': 6,
    'YearsInCurrentRole': 4,
    'YearsSinceLastPromotion': 2,
    'YearsWithCurrManager': 3
}

new_df=pd.DataFrame(new_employee,index=[0])

new_df

prediction=best_model.predict(new_df)

prediction

## reverse encoding

result = le.inverse_transform(prediction)
print(result)

#predict Attrition for new employee or not

if prediction[0] == 1:
    print(" There will be Attrition")
else:
    print("There will no  Attrition")